version: '3.8'

name: reiverr-dev

services:
  reiverr-frontend:
    container_name: reiverr-dev
    image: ghcr.io/aleksilassila/reiverr:latest
    restart: unless-stopped
    volumes:
      - ./config:/config
